# Eleman Islemleri

In [1]:
import numpy as np
s1 = np.random.randint(10, size=5)
s2 = np.random.randint(10, size=5)
s3 = np.random.randint(10, size=5)

In [2]:
s1

array([1, 9, 6, 3, 8])

In [3]:
s2

array([0, 2, 1, 1, 8])

In [4]:
s3

array([1, 3, 8, 0, 7])

In [5]:
sozluk = {"var1": s1
         , "var2": s2
         , "var3": s3}

In [6]:
sozluk

{'var1': array([1, 9, 6, 3, 8]),
 'var2': array([0, 2, 1, 1, 8]),
 'var3': array([1, 3, 8, 0, 7])}

In [8]:
import pandas as pd
df = pd.DataFrame(sozluk)

In [9]:
df

var1  var2  var3
0     1     0     1
1     9     2     3
2     6     1     8
3     3     1     0
4     8     8     7

In [10]:
df[0:1]

var1  var2  var3
0     1     0     1

In [12]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [13]:
df.index = ["a","b","c","d","e"]

In [14]:
df

var1  var2  var3
a     1     0     1
b     9     2     3
c     6     1     8
d     3     1     0
e     8     8     7

In [15]:
df["c":"e"]

var1  var2  var3
c     6     1     8
d     3     1     0
e     8     8     7

In [16]:
#silme

In [17]:
df.drop("a", axis=0)

var1  var2  var3
b     9     2     3
c     6     1     8
d     3     1     0
e     8     8     7

In [18]:
df #goruldugu gibi ana dataframe'den silinmemis oldu.

var1  var2  var3
a     1     0     1
b     9     2     3
c     6     1     8
d     3     1     0
e     8     8     7

In [20]:
df.drop("a", axis=0, inplace= True) #inplace ile DataFrame üzerinde kalıcı degisiklik saglar. Axis kısmında 0 ile satiri belirtmis oluruz.
df

KeyError: "['a'] not found in axis"

In [21]:
df

var1  var2  var3
b     9     2     3
c     6     1     8
d     3     1     0
e     8     8     7

In [22]:
#fancy

In [25]:
l = ["c","e"]

In [28]:
df.drop(l, axis= 0 )

var1  var2  var3
b     9     2     3
d     3     1     0

In [30]:
#degiskenler icin

In [31]:
"var1" in df #var1 bu dataframe icerisinde var mi yok mu? Bunun cevabini getirir.

True

In [32]:
l = ["var1","var2","var4"]

In [33]:
for i in l:
    print(i in df) #indeks bazinda bir sorgulama yaparak bu degiskenlerin olup olmadigini for dongusu ile kontrol etmis olduk.

True
True
False


In [34]:
df

var1  var2  var3
b     9     2     3
c     6     1     8
d     3     1     0
e     8     8     7

In [35]:
df["var4"] = df["var1"] * df["var2"]
df

var1  var2  var3  var4
b     9     2     3    18
c     6     1     8     6
d     3     1     0     3
e     8     8     7    64

In [36]:
#degisken silmek

In [37]:
df.drop("var4", axis=1)

var1  var2  var3
b     9     2     3
c     6     1     8
d     3     1     0
e     8     8     7

In [38]:
df

var1  var2  var3  var4
b     9     2     3    18
c     6     1     8     6
d     3     1     0     3
e     8     8     7    64

In [39]:
df.drop("var4", axis=1, inplace = True)

In [40]:
df

var1  var2  var3
b     9     2     3
c     6     1     8
d     3     1     0
e     8     8     7

In [41]:
l = ["var1", "var2"]

In [42]:
df.drop(l, axis=1)

var3
b     3
c     8
d     0
e     7